# metsis_drupal.index:
#   type: config_object
#   label: 'Metsis Search API Index'
#   mapping:
#     field_settings:
#       type: mapping
#       label: 'Field settings'
#       mapping:
#         metsis_drupal_geojson_field:
#           type: mapping
#           label: 'GeoJSON field settings'
#           mapping:
#             configuration:
#               type: mapping
#               label: 'Configuration'
#               mapping:
#                 geojson_field_value:
#                   type: string
#                   label: 'GeoJSON field value'
