name: Tests (DDEV)

on:
  push:
  pull_request:

jobs:
  paratest-ddev:
    name: Paratest in DDEV
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup DDEV
        uses: ddev/github-action-setup-ddev@v1
      - run: ddev poser && ddev symlink-project
      - run: |
          set -euo pipefail
          PROCESSES="$(nproc || echo 4)"
          ddev exec vendor/bin/paratest --processes="${PROCESSES}"
